platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e34a96a0963fee6d6bf50f6fc184797014464719

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 065639a0a76c5f7c564509b8fd8b64f7949da4f5

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 65dfd28873152b5a62370f34453d072c415b63d3

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: feature/smp
  commit: 9552e2cfcd9c97bcf43a2ac9728f9f268f832235

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: dev-esp32
  commit: e1501e6a01216d944131187cb50f014a74c3f70a

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 53b61a46c27406623cdf7e727a2958aca98a1cda
